### ISSUE TITLE
Remove old bridges?

### ISSUE THREAD

**Issue by karelbilek** [trezor/data#1]
Now we have git-lfs, the repo itself is not big; but because we have all the old bridges at master, they all get downloaded anyway; and then they all get uploaded to our web server when releasing wallet. (they have around 1GB total)

Suggestion: Delete them from master and keep them in a separate branch `old`. Now that we have lfs, the old bridges won't get downloaded when cloning repo.

**Comment by prusnak** [comment]
Already done
