### ISSUE TITLE
Systemd dependency trezor-bridge

### ISSUE THREAD

**Issue by HenryWait** [trezor/data#11]
Trezor-bridge package for Linux has a dependency for systemd. 

This means that distributions without systemd can not install trezor bridge.
- Devuan 
- Gentoo, Arch or Parabola with openRC or other init system
- Void Linux
- And the BSDs (although not linux), OpenBSD, FreeBSD, NetBSD and DragonFly BSD.

Is there a work around for Unix like operating systems without systemd?

**Comment by karelbilek** [comment]
Duplicate with https://github.com/trezor/trezord-go/issues/35

**Comment by prusnak** [comment]
It's the job of these distributions and their maintainers to provide a package (most of them already do) if they decide not to ship with systemd.
