### ISSUE TITLE
Using ElectrumSV with Trezor

### ISSUE THREAD

**Issue by ghost** [trezor/data#15]
I and many other Trezor users have a problem with ElectrumSV. 
Could we have a simple and clear instruction? 

Something like this:
1. ElectrumSV does work only with Trezor firmware version 1.9.0
2. If you have a higher version you have to downgrade your Trezor firmware to version 1.9.0
3. The downgrading instruction is here: https://wiki.trezor.io/Firmware_downgrade
4. .bin file is here: https://........

I was unable to find the .bin file for version 1.9.0

**Comment by prusnak** [comment]
Yes, your guide is right.

FW 1.9.0 is here https://github.com/trezor/webwallet-data/blob/master/firmware/1/trezor-1.9.0.bin

**Comment by ghost** [comment]
Thank you so much!
