### ISSUE TITLE
trezor-bridge installation fails in Qubes Fedora 33

### ISSUE THREAD

**Issue by turn1a** [trezor/data#23]
I've been trying to install trezor-bridge in Qubes' Fedora 33 for the past couple of days and I failed.

First thing I noticed is 2.0.27 is recommended on the trezor.io website, but the newest version in GitHub is 2.0.30. Why is that? Please update the website to point to the newest version.

I tried installing both versions (and every version in between) and failed. Fedora 33 requies the PGP keys used to sign the packages to be imported into the system first. That key was hard to find. I had to go to @prusnak personal website and download the PGP key from there, but that was just an assumption: it is not clearly stated what keys were used and how to obtain them. That key should be accessible and put on the website. Even after importing the key and checking if the package is signed ok (2.0.27) the installation fails:

```
[user@fedora-33]~/Downloads% rpmkeys -K -v trezor-bridge-2.0.27-1.x86_64.rpm 
trezor-bridge-2.0.27-1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID b9a02a3d: OK
    Header SHA1 digest: OK
    V4 RSA/SHA256 Signature, key ID b9a02a3d: OK
    MD5 digest: OK
[user@fedora-33]~/Downloads% sudo dnf install trezor-bridge-2.0.27-1.x86_64.rpm 
Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)
Last metadata expiration check: 0:36:39 ago on Sun May 30 14:50:33 2021.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                               Architecture                                   Version                                           Repository                                            Size
===================================================================================================================================================================================================================
Installing:
 trezor-bridge                                         x86_64                                         2.0.27-1                                          @commandline                                         4.8 M

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total size: 4.8 M
Installed size: 10 M
Is this ok [y/N]: y
Downloading Packages:
error: trezor-bridge-2.0.27-1.x86_64.rpm: open failed: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 201, in user_main
    errcode = main(args)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 130, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 176, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.9/site-packages/dnf/cli/cli.py", line 238, in do_transaction
    self.gpgsigcheck(install_pkgs)
  File "/usr/lib/python3.9/site-packages/dnf/cli/cli.py", line 278, in gpgsigcheck
    result, errmsg = self._sig_check_pkg(po)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 1297, in _sig_check_pkg
    sigresult = dnf.rpm.miscutils.checkSig(ts, po.localPkg())
  File "/usr/lib/python3.9/site-packages/dnf/rpm/miscutils.py", line 90, in checkSig
    raise ValueError('Unexpected return value %r from hdr.sprintf when checking signature.' % siginfo)
ValueError: Unexpected return value 'RSA/SHA256, Mon May 13 13:58:02 2019, Key ID 91f3b339b9a02a3d' from hdr.sprintf when checking signature.
```

I have no idea what the issue is. The installation fails for 2.0.27, 2.0.28 and 2.0.29. It seems that packages are somehow broken. Please see this RedHat issue: https://bugzilla.redhat.com/show_bug.cgi?id=1963732

I also tried to install the newest 2.0.30 version, but it's signed with different key which I haven't been able to find anywhere:

```
[user@fedora-33]~/Downloads% rpmkeys -K -v trezor-bridge-2.0.30-1.x86_64.rpm   
trezor-bridge-2.0.30-1.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 62f0e7e2: NOKEY
    Header DSA signature: NOTFOUND
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA256 Signature, key ID 62f0e7e2: NOKEY
    DSA signature: NOTFOUND
    MD5 digest: OK
```

Even if I had that key I would probably encounter the same issue as above. I've run out of options here. Am I using the right key? Why the package installation fails? Why the website points to an old package? Why the newest package is signed with different key and where to find it?

**Comment by turn1a** [comment]
I managed to install versions up to `20.0.29` using `sudo dnf localinstall` and `sudo rpm -i`. The question about the signing key for `20.0.30` still remains as well as the request to make the PGP signing key for previous version to be easily accessible.

**Comment by prusnak** [comment]
The signing key for bridge 2.0.30 is available from https://trezor.io/security/satoshilabs-2020-signing-key.asc

I feel your pain, but it's impossible to support all possible Linux distributions at once. At best we can ask you to find someone from Fedora project to package and maintain trezor bridge within the Fedora distribution. That would provide the best security and user experience. Thanks for understanding.
