### ISSUE TITLE
Rename model-specific firmware directories to UPPERCASE

### ISSUE THREAD

**Issue by matejcik** [trezor/data#63]
`t1b1` -> `T1B1`
`t2t1` -> `T2T1`

The internal names are not "symbols", they are constants, and as such are implicitly case sensitive.

If we are not using the new paths anywhere yet (@mroz22 please confirm), please rename.

**Comment by vdovhanych** [comment]
What about the firmware file name? Is that also supposed to be uppercase?

**Comment by matejcik** [comment]
That does not matter to me.
Our build artifacts come out with uppercase names.
When looking up the file to download, I will retrieve the filename from `releases.json`, I don't think I am ever going to be interpolating `trezor-{model}-{version}.bin`.

For consistency, it would make sense to make them uppercase. Maybe Connect has some opinions?

**Comment by matejcik** [comment]
the lowercase names are already consumed by production Suite so this is not worth the compatibility hassle
