### ISSUE TITLE
add t2b1 firmwares 

### ISSUE THREAD

**Issue by vdovhanych** [trezor/data#64]
add t2b1 firmware and related stuff

**Comment by vdovhanych** [comment]
#65

**Comment by CodeShakingSheep** [comment]
According to the [firmware changelog](https://trezor.io/learn/a/firmware-changelog) firmware 2.6.4 was released last week. I wanted to update my trezor to it and verify the fingerprint but it's not yet in https://github.com/trezor/data/blob/master/firmware/2/releases.json. Can you update it? Thanks.

**Comment by vdovhanych** [comment]
Hey, thanks for pointing it out. I opened a PR with new firmware, which should be merged here soon. 
Also, closing this issue as it was resolved.
