### ISSUE TITLE
Bridge latest version

### ISSUE THREAD

**Issue by posadzka** [trezor/data#67]
Hi!

Any particular reson why latest bridge version point to 2.0.27 and not to 2.0.30? 2.0.27 is also offered on web wallet when no bridge is installed.

**Comment by vdovhanych** [comment]
Hey there, yeah, that is correct. We decided not to release the newer version as a standalone bridge, and it's bundled with the suite only. We are also currently in the process of reworking the bridge in favor of native solution [transport-bridge](https://github.com/trezor/trezor-suite/tree/develop/packages/transport-bridge) in the trezor-suite monorepo.
